### ISSUE TITLE
Document search service filter options & parameters

### ISSUE THREAD

**Issue by mhaack** [Adobe-Marketing-Cloud/commerce-cif-doc#9]
Document the search + facets implementation, especially how the filters are used. For example all search filters like _variants.sku_, possible other filters, possible combinations, sorting, pagination. This is at the moment hidden and not documented.

**Comment by develpr** [comment]
+1

This would be super helpful, especially because there is going to be a need (at least in a few commerce systems I'm aware of) to map a CIF2 filter to a specific filter in the underlying commerce system. So having a list of these possible filters / options / parameters would be super useful!
